services:
    rabbitmqeightshop:
        image: rabbitmq:3-management
        container_name: rabbitmqeightshop
        restart: always
        ports: 
            - 5672:5672
            - 15672:15672
        volumes: 
            - ./rabbitmqdata:/var/lib/rabbitmq/
        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin
       